// Copyright (c) Amer Koleci and contributors.
// Distributed under the MIT license. See the LICENSE file in the project root for more information.

using System;

namespace SharpSPIRVCross
{
    public static class SPIRV
    {
        public const uint MagicNumber = 0x07230203;
        public const uint Version = 0x00010300;
        public const uint Revision = 6;
        public const uint OpCodeMask = 0xffff;
        public const uint WordCountShift = 16;
    }

    public enum SpvSourceLanguage
    {
        Unknown = 0,
        ESSL = 1,
        GLSL = 2,
        OpenCL_C = 3,
        OpenCL_CPP = 4,
        HLSL = 5
    }

    public enum SpvExecutionModel
    {
        Vertex = 0,
        TessellationControl = 1,
        TessellationEvaluation = 2,
        Geometry = 3,
        Fragment = 4,
        GLCompute = 5,
        Kernel = 6,
        TaskNV = 5267,
        MeshNV = 5268,
        RayGenerationNV = 5313,
        IntersectionNV = 5314,
        AnyHitNV = 5315,
        ClosestHitNV = 5316,
        MissNV = 5317,
        CallableNV = 5318
    }

    public enum SpvAddressingModel
    {
        Logical = 0,
        Physical32 = 1,
        Physical64 = 2,
        PhysicalStorageBuffer64EXT = 5348
    }

    public enum SpvMemoryModel
    {
        Simple = 0,
        GLSL450 = 1,
        OpenCL = 2,
        VulkanKHR = 3
    }

    public enum SpvExecutionMode
    {
        Invocations = 0,
        SpacingEqual = 1,
        SpacingFractionalEven = 2,
        SpacingFractionalOdd = 3,
        VertexOrderCw = 4,
        VertexOrderCcw = 5,
        PixelCenterInteger = 6,
        OriginUpperLeft = 7,
        OriginLowerLeft = 8,
        EarlyFragmentTests = 9,
        PointMode = 10,
        Xfb = 11,
        DepthReplacing = 12,
        DepthGreater = 14,
        DepthLess = 15,
        DepthUnchanged = 16,
        LocalSize = 17,
        LocalSizeHint = 18,
        InputPoints = 19,
        InputLines = 20,
        InputLinesAdjacency = 21,
        Triangles = 22,
        InputTrianglesAdjacency = 23,
        Quads = 24,
        Isolines = 25,
        OutputVertices = 26,
        OutputPoints = 27,
        OutputLineStrip = 28,
        OutputTriangleStrip = 29,
        VecTypeHint = 30,
        ContractionOff = 31,
        Initializer = 33,
        Finalizer = 34,
        SubgroupSize = 35,
        SubgroupsPerWorkgroup = 36,
        SubgroupsPerWorkgroupId = 37,
        LocalSizeId = 38,
        LocalSizeHintId = 39,
        PostDepthCoverage = 4446,
        DenormPreserve = 4459,
        DenormFlushToZero = 4460,
        SignedZeroInfNanPreserve = 4461,
        RoundingModeRTE = 4462,
        RoundingModeRTZ = 4463,
        StencilRefReplacingEXT = 5027,
        OutputLinesNV = 5269,
        OutputPrimitivesNV = 5270,
        DerivativeGroupQuadsNV = 5289,
        DerivativeGroupLinearNV = 5290,
        OutputTrianglesNV = 5298
    }

    public enum SpvStorageClass
    {
        UniformConstant = 0,
        Input = 1,
        Uniform = 2,
        Output = 3,
        Workgroup = 4,
        CrossWorkgroup = 5,
        Private = 6,
        Function = 7,
        Generic = 8,
        PushConstant = 9,
        AtomicCounter = 10,
        Image = 11,
        StorageBuffer = 12,
        CallableDataNV = 5328,
        IncomingCallableDataNV = 5329,
        RayPayloadNV = 5338,
        HitAttributeNV = 5339,
        IncomingRayPayloadNV = 5342,
        ShaderRecordBufferNV = 5343,
        PhysicalStorageBufferEXT = 5349
    }

    public enum SpvDim
    {
        Dim1D = 0,
        Dim2D = 1,
        Dim3D = 2,
        DimCube = 3,
        DimRect = 4,
        DimBuffer = 5,
        DimSubpassData = 6
    }

    public enum SpvSamplerAddressingMode
    {
        None = 0,
        ClampToEdge = 1,
        Clamp = 2,
        Repeat = 3,
        RepeatMirrored = 4
    }

    public enum SpvSamplerFilterMode
    {
        Nearest = 0,
        Linear = 1
    }

    public enum SpvImageFormat
    {
        Unknown = 0,
        Rgba32f = 1,
        Rgba16f = 2,
        R32f = 3,
        Rgba8 = 4,
        Rgba8Snorm = 5,
        Rg32f = 6,
        Rg16f = 7,
        R11fG11fB10f = 8,
        R16f = 9,
        Rgba16 = 10,
        Rgb10A2 = 11,
        Rg16 = 12,
        Rg8 = 13,
        R16 = 14,
        R8 = 15,
        Rgba16Snorm = 16,
        Rg16Snorm = 17,
        Rg8Snorm = 18,
        R16Snorm = 19,
        R8Snorm = 20,
        Rgba32i = 21,
        Rgba16i = 22,
        Rgba8i = 23,
        R32i = 24,
        Rg32i = 25,
        Rg16i = 26,
        Rg8i = 27,
        R16i = 28,
        R8i = 29,
        Rgba32ui = 30,
        Rgba16ui = 31,
        Rgba8ui = 32,
        R32ui = 33,
        Rgb10a2ui = 34,
        Rg32ui = 35,
        Rg16ui = 36,
        Rg8ui = 37,
        R16ui = 38,
        R8ui = 39
    }

    public enum SpvImageChannelOrder
    {
        R = 0,
        A = 1,
        RG = 2,
        RA = 3,
        RGB = 4,
        RGBA = 5,
        BGRA = 6,
        ARGB = 7,
        Intensity = 8,
        Luminance = 9,
        Rx = 10,
        RGx = 11,
        RGBx = 12,
        Depth = 13,
        DepthStencil = 14,
        sRGB = 15,
        sRGBx = 16,
        sRGBA = 17,
        sBGRA = 18,
        ABGR = 19
    }

    public enum SpvImageChannelDataType
    {
        SnormInt8 = 0,
        SnormInt16 = 1,
        UnormInt8 = 2,
        UnormInt16 = 3,
        UnormShort565 = 4,
        UnormShort555 = 5,
        UnormInt101010 = 6,
        SignedInt8 = 7,
        SignedInt16 = 8,
        SignedInt32 = 9,
        UnsignedInt8 = 10,
        UnsignedInt16 = 11,
        UnsignedInt32 = 12,
        HalfFloat = 13,
        Float = 14,
        UnormInt24 = 15,
        UnormInt101010_2 = 16
    }

    public enum SpvImageOperandsShift
    {
        BiasShift = 0,
        LodShift = 1,
        GradShift = 2,
        ConstOffsetShift = 3,
        OffsetShift = 4,
        ConstOffsetsShift = 5,
        SampleShift = 6,
        MinLodShift = 7,
        MakeTexelAvailableKHRShift = 8,
        MakeTexelVisibleKHRShift = 9,
        NonPrivateTexelKHRShift = 10,
        VolatileTexelKHRShift = 11
    }

    [Flags]
    public enum SpvImageOperandsMask
    {
        None = 0,
        BiasMask = 0x00000001,
        LodMask = 0x00000002,
        GradMask = 0x00000004,
        ConstOffsetMask = 0x00000008,
        OffsetMask = 0x00000010,
        ConstOffsetsMask = 0x00000020,
        SampleMask = 0x00000040,
        MinLodMask = 0x00000080,
        MakeTexelAvailableKHRMask = 0x00000100,
        MakeTexelVisibleKHRMask = 0x00000200,
        NonPrivateTexelKHRMask = 0x00000400,
        VolatileTexelKHRMask = 0x00000800,
    }

    public enum SpvFPFastMathModeShift
    {
        NotNaNShift = 0,
        NotInfShift = 1,
        NSZShift = 2,
        AllowRecipShift = 3,
        FastShift = 4
    }

    [Flags]
    public enum SpvFPFastMathModeMask
    {
        None = 0,
        NotNaNMask = 0x00000001,
        NotInfMask = 0x00000002,
        NSZMask = 0x00000004,
        AllowRecipMask = 0x00000008,
        FastMask = 0x00000010,
    }

    public enum SpvFPRoundingMode
    {
        RTE = 0,
        RTZ = 1,
        RTP = 2,
        RTN = 3
    }

    public enum SpvLinkageType
    {
        Export = 0,
        Import = 1
    }

    public enum SpvAccessQualifier
    {
        ReadOnly = 0,
        WriteOnly = 1,
        ReadWrite = 2
    }

    public enum SpvFunctionParameterAttribute
    {
        Zext = 0,
        Sext = 1,
        ByVal = 2,
        Sret = 3,
        NoAlias = 4,
        NoCapture = 5,
        NoWrite = 6,
        NoReadWrite = 7
    }

    public enum SpvDecoration
    {
        RelaxedPrecision = 0,
        SpecId = 1,
        Block = 2,
        BufferBlock = 3,
        RowMajor = 4,
        ColMajor = 5,
        ArrayStride = 6,
        MatrixStride = 7,
        GLSLShared = 8,
        GLSLPacked = 9,
        CPacked = 10,
        BuiltIn = 11,
        NoPerspective = 13,
        Flat = 14,
        Patch = 15,
        Centroid = 16,
        Sample = 17,
        Invariant = 18,
        Restrict = 19,
        Aliased = 20,
        Volatile = 21,
        Constant = 22,
        Coherent = 23,
        NonWritable = 24,
        NonReadable = 25,
        Uniform = 26,
        SaturatedConversion = 28,
        Stream = 29,
        Location = 30,
        Component = 31,
        Index = 32,
        Binding = 33,
        DescriptorSet = 34,
        Offset = 35,
        XfbBuffer = 36,
        XfbStride = 37,
        FuncParamAttr = 38,
        FPRoundingMode = 39,
        FPFastMathMode = 40,
        LinkageAttributes = 41,
        NoContraction = 42,
        InputAttachmentIndex = 43,
        Alignment = 44,
        MaxByteOffset = 45,
        AlignmentId = 46,
        MaxByteOffsetId = 47,
        NoSignedWrap = 4469,
        NoUnsignedWrap = 4470,
        ExplicitInterpAMD = 4999,
        OverrideCoverageNV = 5248,
        PassthroughNV = 5250,
        ViewportRelativeNV = 5252,
        SecondaryViewportRelativeNV = 5256,
        PerPrimitiveNV = 5271,
        PerViewNV = 5272,
        PerTaskNV = 5273,
        PerVertexNV = 5285,
        NonUniformEXT = 5300,
        RestrictPointerEXT = 5355,
        AliasedPointerEXT = 5356,
        HlslCounterBufferGOOGLE = 5634,
        HlslSemanticGOOGLE = 5635
    }

    public enum SpvBuiltIn
    {
        Position = 0,
        PointSize = 1,
        ClipDistance = 3,
        CullDistance = 4,
        VertexId = 5,
        InstanceId = 6,
        PrimitiveId = 7,
        InvocationId = 8,
        Layer = 9,
        ViewportIndex = 10,
        TessLevelOuter = 11,
        TessLevelInner = 12,
        TessCoord = 13,
        PatchVertices = 14,
        FragCoord = 15,
        PointCoord = 16,
        FrontFacing = 17,
        SampleId = 18,
        SamplePosition = 19,
        SampleMask = 20,
        FragDepth = 22,
        HelperInvocation = 23,
        NumWorkgroups = 24,
        WorkgroupSize = 25,
        WorkgroupId = 26,
        LocalInvocationId = 27,
        GlobalInvocationId = 28,
        LocalInvocationIndex = 29,
        WorkDim = 30,
        GlobalSize = 31,
        EnqueuedWorkgroupSize = 32,
        GlobalOffset = 33,
        GlobalLinearId = 34,
        SubgroupSize = 36,
        SubgroupMaxSize = 37,
        NumSubgroups = 38,
        NumEnqueuedSubgroups = 39,
        SubgroupId = 40,
        SubgroupLocalInvocationId = 41,
        VertexIndex = 42,
        InstanceIndex = 43,
        SubgroupEqMask = 4416,
        SubgroupEqMaskKHR = 4416,
        SubgroupGeMask = 4417,
        SubgroupGeMaskKHR = 4417,
        SubgroupGtMask = 4418,
        SubgroupGtMaskKHR = 4418,
        SubgroupLeMask = 4419,
        SubgroupLeMaskKHR = 4419,
        SubgroupLtMask = 4420,
        SubgroupLtMaskKHR = 4420,
        BaseVertex = 4424,
        BaseInstance = 4425,
        DrawIndex = 4426,
        DeviceIndex = 4438,
        ViewIndex = 4440,
        BaryCoordNoPerspAMD = 4992,
        BaryCoordNoPerspCentroidAMD = 4993,
        BaryCoordNoPerspSampleAMD = 4994,
        BaryCoordSmoothAMD = 4995,
        BaryCoordSmoothCentroidAMD = 4996,
        BaryCoordSmoothSampleAMD = 4997,
        BaryCoordPullModelAMD = 4998,
        FragStencilRefEXT = 5014,
        ViewportMaskNV = 5253,
        SecondaryPositionNV = 5257,
        SecondaryViewportMaskNV = 5258,
        PositionPerViewNV = 5261,
        ViewportMaskPerViewNV = 5262,
        FullyCoveredEXT = 5264,
        TaskCountNV = 5274,
        PrimitiveCountNV = 5275,
        PrimitiveIndicesNV = 5276,
        ClipDistancePerViewNV = 5277,
        CullDistancePerViewNV = 5278,
        LayerPerViewNV = 5279,
        MeshViewCountNV = 5280,
        MeshViewIndicesNV = 5281,
        BaryCoordNV = 5286,
        BaryCoordNoPerspNV = 5287,
        FragSizeEXT = 5292,
        FragmentSizeNV = 5292,
        FragInvocationCountEXT = 5293,
        InvocationsPerPixelNV = 5293,
        LaunchIdNV = 5319,
        LaunchSizeNV = 5320,
        WorldRayOriginNV = 5321,
        WorldRayDirectionNV = 5322,
        ObjectRayOriginNV = 5323,
        ObjectRayDirectionNV = 5324,
        RayTminNV = 5325,
        RayTmaxNV = 5326,
        InstanceCustomIndexNV = 5327,
        ObjectToWorldNV = 5330,
        WorldToObjectNV = 5331,
        HitTNV = 5332,
        HitKindNV = 5333,
        IncomingRayFlagsNV = 5351
    }

    public enum SpvSelectionControlShift
    {
        FlattenShift = 0,
        DontFlattenShift = 1
    }

    [Flags]
    public enum SpvSelectionControlMask
    {
        None = 0,
        FlattenMask = 0x00000001,
        DontFlattenMask = 0x00000002,
    }

    public enum SpvLoopControlShift
    {
        UnrollShift = 0,
        DontUnrollShift = 1,
        DependencyInfiniteShift = 2,
        DependencyLengthShift = 3
    }

    [Flags]
    public enum SpvLoopControlMask
    {
        None = 0,
        UnrollMask = 0x00000001,
        DontUnrollMask = 0x00000002,
        DependencyInfiniteMask = 0x00000004,
        DependencyLengthMask = 0x00000008,
    }

    public enum SpvFunctionControlShift
    {
        InlineShift = 0,
        DontInlineShift = 1,
        PureShift = 2,
        ConstShift = 3
    }

    [Flags]
    public enum SpvFunctionControlMask
    {
        MaskNone = 0,
        InlineMask = 0x00000001,
        DontInlineMask = 0x00000002,
        PureMask = 0x00000004,
        ConstMask = 0x00000008,
    }

    public enum SpvMemorySemanticsShift
    {
        AcquireShift = 1,
        ReleaseShift = 2,
        AcquireReleaseShift = 3,
        SequentiallyConsistentShift = 4,
        UniformMemoryShift = 6,
        SubgroupMemoryShift = 7,
        WorkgroupMemoryShift = 8,
        CrossWorkgroupMemoryShift = 9,
        AtomicCounterMemoryShift = 10,
        ImageMemoryShift = 11,
        OutputMemoryKHRShift = 12,
        MakeAvailableKHRShift = 13,
        MakeVisibleKHRShift = 14
    }

    [Flags]
    public enum SpvMemorySemanticsMask
    {
        None = 0,
        AcquireMask = 0x00000002,
        ReleaseMask = 0x00000004,
        AcquireReleaseMask = 0x00000008,
        SequentiallyConsistentMask = 0x00000010,
        UniformMemoryMask = 0x00000040,
        SubgroupMemoryMask = 0x00000080,
        WorkgroupMemoryMask = 0x00000100,
        CrossWorkgroupMemoryMask = 0x00000200,
        AtomicCounterMemoryMask = 0x00000400,
        ImageMemoryMask = 0x00000800,
        OutputMemoryKHRMask = 0x00001000,
        MakeAvailableKHRMask = 0x00002000,
        MakeVisibleKHRMask = 0x00004000,
    }

    public enum SpvMemoryAccessShift
    {
        VolatileShift = 0,
        AlignedShift = 1,
        NontemporalShift = 2,
        MakePointerAvailableKHRShift = 3,
        MakePointerVisibleKHRShift = 4,
        NonPrivatePointerKHRShift = 5
    }

    [Flags]
    public enum SpvMemoryAccessMask
    {
        None = 0,
        VolatileMask = 0x00000001,
        AlignedMask = 0x00000002,
        NontemporalMask = 0x00000004,
        MakePointerAvailableKHRMask = 0x00000008,
        MakePointerVisibleKHRMask = 0x00000010,
        NonPrivatePointerKHRMask = 0x00000020,
    }

    public enum SpvScope
    {
        CrossDevice = 0,
        Device = 1,
        Workgroup = 2,
        Subgroup = 3,
        Invocation = 4,
        QueueFamilyKHR = 5
    }

    public enum SpvGroupOperation
    {
        Reduce = 0,
        InclusiveScan = 1,
        ExclusiveScan = 2,
        ClusteredReduce = 3,
        PartitionedReduceNV = 6,
        PartitionedInclusiveScanNV = 7,
        PartitionedExclusiveScanNV = 8
    }

    public enum SpvKernelEnqueueFlags
    {
        NoWait = 0,
        WaitKernel = 1,
        WaitWorkGroup = 2
    }

    public enum SpvKernelProfilingInfoShift
    {
        CmdExecTimeShift = 0
    }

    public enum SpvKernelProfilingInfoMask
    {
        MaskNone = 0,
        CmdExecTimeMask = 0x00000001,
    }

    public enum SpvCapability
    {
        Matrix = 0,
        Shader = 1,
        Geometry = 2,
        Tessellation = 3,
        Addresses = 4,
        Linkage = 5,
        Kernel = 6,
        Vector16 = 7,
        Float16Buffer = 8,
        Float16 = 9,
        Float64 = 10,
        Int64 = 11,
        Int64Atomics = 12,
        ImageBasic = 13,
        ImageReadWrite = 14,
        ImageMipmap = 15,
        Pipes = 17,
        Groups = 18,
        DeviceEnqueue = 19,
        LiteralSampler = 20,
        AtomicStorage = 21,
        Int16 = 22,
        TessellationPointSize = 23,
        GeometryPointSize = 24,
        ImageGatherExtended = 25,
        StorageImageMultisample = 27,
        UniformBufferArrayDynamicIndexing = 28,
        SampledImageArrayDynamicIndexing = 29,
        StorageBufferArrayDynamicIndexing = 30,
        StorageImageArrayDynamicIndexing = 31,
        ClipDistance = 32,
        CullDistance = 33,
        ImageCubeArray = 34,
        SampleRateShading = 35,
        ImageRect = 36,
        SampledRect = 37,
        GenericPointer = 38,
        Int8 = 39,
        InputAttachment = 40,
        SparseResidency = 41,
        MinLod = 42,
        Sampled1D = 43,
        Image1D = 44,
        SampledCubeArray = 45,
        SampledBuffer = 46,
        ImageBuffer = 47,
        ImageMSArray = 48,
        StorageImageExtendedFormats = 49,
        ImageQuery = 50,
        DerivativeControl = 51,
        InterpolationFunction = 52,
        TransformFeedback = 53,
        GeometryStreams = 54,
        StorageImageReadWithoutFormat = 55,
        StorageImageWriteWithoutFormat = 56,
        MultiViewport = 57,
        SubgroupDispatch = 58,
        NamedBarrier = 59,
        PipeStorage = 60,
        GroupNonUniform = 61,
        GroupNonUniformVote = 62,
        GroupNonUniformArithmetic = 63,
        GroupNonUniformBallot = 64,
        GroupNonUniformShuffle = 65,
        GroupNonUniformShuffleRelative = 66,
        GroupNonUniformClustered = 67,
        GroupNonUniformQuad = 68,
        SubgroupBallotKHR = 4423,
        DrawParameters = 4427,
        SubgroupVoteKHR = 4431,
        StorageBuffer16BitAccess = 4433,
        StorageUniformBufferBlock16 = 4433,
        StorageUniform16 = 4434,
        UniformAndStorageBuffer16BitAccess = 4434,
        StoragePushConstant16 = 4435,
        StorageInputOutput16 = 4436,
        DeviceGroup = 4437,
        MultiView = 4439,
        VariablePointersStorageBuffer = 4441,
        VariablePointers = 4442,
        AtomicStorageOps = 4445,
        SampleMaskPostDepthCoverage = 4447,
        StorageBuffer8BitAccess = 4448,
        UniformAndStorageBuffer8BitAccess = 4449,
        StoragePushConstant8 = 4450,
        DenormPreserve = 4464,
        DenormFlushToZero = 4465,
        SignedZeroInfNanPreserve = 4466,
        RoundingModeRTE = 4467,
        RoundingModeRTZ = 4468,
        Float16ImageAMD = 5008,
        ImageGatherBiasLodAMD = 5009,
        FragmentMaskAMD = 5010,
        StencilExportEXT = 5013,
        ImageReadWriteLodAMD = 5015,
        SampleMaskOverrideCoverageNV = 5249,
        GeometryShaderPassthroughNV = 5251,
        ShaderViewportIndexLayerEXT = 5254,
        ShaderViewportIndexLayerNV = 5254,
        ShaderViewportMaskNV = 5255,
        ShaderStereoViewNV = 5259,
        PerViewAttributesNV = 5260,
        FragmentFullyCoveredEXT = 5265,
        MeshShadingNV = 5266,
        ImageFootprintNV = 5282,
        FragmentBarycentricNV = 5284,
        ComputeDerivativeGroupQuadsNV = 5288,
        FragmentDensityEXT = 5291,
        ShadingRateNV = 5291,
        GroupNonUniformPartitionedNV = 5297,
        ShaderNonUniformEXT = 5301,
        RuntimeDescriptorArrayEXT = 5302,
        InputAttachmentArrayDynamicIndexingEXT = 5303,
        UniformTexelBufferArrayDynamicIndexingEXT = 5304,
        StorageTexelBufferArrayDynamicIndexingEXT = 5305,
        UniformBufferArrayNonUniformIndexingEXT = 5306,
        SampledImageArrayNonUniformIndexingEXT = 5307,
        StorageBufferArrayNonUniformIndexingEXT = 5308,
        StorageImageArrayNonUniformIndexingEXT = 5309,
        InputAttachmentArrayNonUniformIndexingEXT = 5310,
        UniformTexelBufferArrayNonUniformIndexingEXT = 5311,
        StorageTexelBufferArrayNonUniformIndexingEXT = 5312,
        RayTracingNV = 5340,
        VulkanMemoryModelKHR = 5345,
        VulkanMemoryModelDeviceScopeKHR = 5346,
        PhysicalStorageBufferAddressesEXT = 5347,
        ComputeDerivativeGroupLinearNV = 5350,
        CooperativeMatrixNV = 5357,
        SubgroupShuffleINTEL = 5568,
        SubgroupBufferBlockIOINTEL = 5569,
        SubgroupImageBlockIOINTEL = 5570,
        SubgroupImageMediaBlockIOINTEL = 5579
    }

    public enum SpvOp
    {
        Nop = 0,
        Undef = 1,
        SourceContinued = 2,
        Source = 3,
        SourceExtension = 4,
        Name = 5,
        MemberName = 6,
        String = 7,
        Line = 8,
        Extension = 10,
        ExtInstImport = 11,
        ExtInst = 12,
        MemoryModel = 14,
        EntryPoint = 15,
        ExecutionMode = 16,
        Capability = 17,
        TypeVoid = 19,
        TypeBool = 20,
        TypeInt = 21,
        TypeFloat = 22,
        TypeVector = 23,
        TypeMatrix = 24,
        TypeImage = 25,
        TypeSampler = 26,
        TypeSampledImage = 27,
        TypeArray = 28,
        TypeRuntimeArray = 29,
        TypeStruct = 30,
        TypeOpaque = 31,
        TypePointer = 32,
        TypeFunction = 33,
        TypeEvent = 34,
        TypeDeviceEvent = 35,
        TypeReserveId = 36,
        TypeQueue = 37,
        TypePipe = 38,
        TypeForwardPointer = 39,
        ConstantTrue = 41,
        ConstantFalse = 42,
        Constant = 43,
        ConstantComposite = 44,
        ConstantSampler = 45,
        ConstantNull = 46,
        SpecConstantTrue = 48,
        SpecConstantFalse = 49,
        SpecConstant = 50,
        SpecConstantComposite = 51,
        SpecConstantOp = 52,
        Function = 54,
        FunctionParameter = 55,
        FunctionEnd = 56,
        FunctionCall = 57,
        Variable = 59,
        ImageTexelPointer = 60,
        Load = 61,
        Store = 62,
        CopyMemory = 63,
        CopyMemorySized = 64,
        AccessChain = 65,
        InBoundsAccessChain = 66,
        PtrAccessChain = 67,
        ArrayLength = 68,
        GenericPtrMemSemantics = 69,
        InBoundsPtrAccessChain = 70,
        Decorate = 71,
        MemberDecorate = 72,
        DecorationGroup = 73,
        GroupDecorate = 74,
        GroupMemberDecorate = 75,
        VectorExtractDynamic = 77,
        VectorInsertDynamic = 78,
        VectorShuffle = 79,
        CompositeConstruct = 80,
        CompositeExtract = 81,
        CompositeInsert = 82,
        CopyObject = 83,
        Transpose = 84,
        SampledImage = 86,
        ImageSampleImplicitLod = 87,
        ImageSampleExplicitLod = 88,
        ImageSampleDrefImplicitLod = 89,
        ImageSampleDrefExplicitLod = 90,
        ImageSampleProjImplicitLod = 91,
        ImageSampleProjExplicitLod = 92,
        ImageSampleProjDrefImplicitLod = 93,
        ImageSampleProjDrefExplicitLod = 94,
        ImageFetch = 95,
        ImageGather = 96,
        ImageDrefGather = 97,
        ImageRead = 98,
        ImageWrite = 99,
        Image = 100,
        ImageQueryFormat = 101,
        ImageQueryOrder = 102,
        ImageQuerySizeLod = 103,
        ImageQuerySize = 104,
        ImageQueryLod = 105,
        ImageQueryLevels = 106,
        ImageQuerySamples = 107,
        ConvertFToU = 109,
        ConvertFToS = 110,
        ConvertSToF = 111,
        ConvertUToF = 112,
        UConvert = 113,
        SConvert = 114,
        FConvert = 115,
        QuantizeToF16 = 116,
        ConvertPtrToU = 117,
        SatConvertSToU = 118,
        SatConvertUToS = 119,
        ConvertUToPtr = 120,
        PtrCastToGeneric = 121,
        GenericCastToPtr = 122,
        GenericCastToPtrExplicit = 123,
        Bitcast = 124,
        SNegate = 126,
        FNegate = 127,
        IAdd = 128,
        FAdd = 129,
        ISub = 130,
        FSub = 131,
        IMul = 132,
        FMul = 133,
        UDiv = 134,
        SDiv = 135,
        FDiv = 136,
        UMod = 137,
        SRem = 138,
        SMod = 139,
        FRem = 140,
        FMod = 141,
        VectorTimesScalar = 142,
        MatrixTimesScalar = 143,
        VectorTimesMatrix = 144,
        MatrixTimesVector = 145,
        MatrixTimesMatrix = 146,
        OuterProduct = 147,
        Dot = 148,
        IAddCarry = 149,
        ISubBorrow = 150,
        UMulExtended = 151,
        SMulExtended = 152,
        Any = 154,
        All = 155,
        IsNan = 156,
        IsInf = 157,
        IsFinite = 158,
        IsNormal = 159,
        SignBitSet = 160,
        LessOrGreater = 161,
        Ordered = 162,
        Unordered = 163,
        LogicalEqual = 164,
        LogicalNotEqual = 165,
        LogicalOr = 166,
        LogicalAnd = 167,
        LogicalNot = 168,
        Select = 169,
        IEqual = 170,
        INotEqual = 171,
        UGreaterThan = 172,
        SGreaterThan = 173,
        UGreaterThanEqual = 174,
        SGreaterThanEqual = 175,
        ULessThan = 176,
        SLessThan = 177,
        ULessThanEqual = 178,
        SLessThanEqual = 179,
        FOrdEqual = 180,
        FUnordEqual = 181,
        FOrdNotEqual = 182,
        FUnordNotEqual = 183,
        FOrdLessThan = 184,
        FUnordLessThan = 185,
        FOrdGreaterThan = 186,
        FUnordGreaterThan = 187,
        FOrdLessThanEqual = 188,
        FUnordLessThanEqual = 189,
        FOrdGreaterThanEqual = 190,
        FUnordGreaterThanEqual = 191,
        ShiftRightLogical = 194,
        ShiftRightArithmetic = 195,
        ShiftLeftLogical = 196,
        BitwiseOr = 197,
        BitwiseXor = 198,
        BitwiseAnd = 199,
        Not = 200,
        BitFieldInsert = 201,
        BitFieldSExtract = 202,
        BitFieldUExtract = 203,
        BitReverse = 204,
        BitCount = 205,
        DPdx = 207,
        DPdy = 208,
        Fwidth = 209,
        DPdxFine = 210,
        DPdyFine = 211,
        FwidthFine = 212,
        DPdxCoarse = 213,
        DPdyCoarse = 214,
        FwidthCoarse = 215,
        EmitVertex = 218,
        EndPrimitive = 219,
        EmitStreamVertex = 220,
        EndStreamPrimitive = 221,
        ControlBarrier = 224,
        MemoryBarrier = 225,
        AtomicLoad = 227,
        AtomicStore = 228,
        AtomicExchange = 229,
        AtomicCompareExchange = 230,
        AtomicCompareExchangeWeak = 231,
        AtomicIIncrement = 232,
        AtomicIDecrement = 233,
        AtomicIAdd = 234,
        AtomicISub = 235,
        AtomicSMin = 236,
        AtomicUMin = 237,
        AtomicSMax = 238,
        AtomicUMax = 239,
        AtomicAnd = 240,
        AtomicOr = 241,
        AtomicXor = 242,
        Phi = 245,
        LoopMerge = 246,
        SelectionMerge = 247,
        Label = 248,
        Branch = 249,
        BranchConditional = 250,
        Switch = 251,
        Kill = 252,
        Return = 253,
        ReturnValue = 254,
        Unreachable = 255,
        LifetimeStart = 256,
        LifetimeStop = 257,
        GroupAsyncCopy = 259,
        GroupWaitEvents = 260,
        GroupAll = 261,
        GroupAny = 262,
        GroupBroadcast = 263,
        GroupIAdd = 264,
        GroupFAdd = 265,
        GroupFMin = 266,
        GroupUMin = 267,
        GroupSMin = 268,
        GroupFMax = 269,
        GroupUMax = 270,
        GroupSMax = 271,
        ReadPipe = 274,
        WritePipe = 275,
        ReservedReadPipe = 276,
        ReservedWritePipe = 277,
        ReserveReadPipePackets = 278,
        ReserveWritePipePackets = 279,
        CommitReadPipe = 280,
        CommitWritePipe = 281,
        IsValidReserveId = 282,
        GetNumPipePackets = 283,
        GetMaxPipePackets = 284,
        GroupReserveReadPipePackets = 285,
        GroupReserveWritePipePackets = 286,
        GroupCommitReadPipe = 287,
        GroupCommitWritePipe = 288,
        EnqueueMarker = 291,
        EnqueueKernel = 292,
        GetKernelNDrangeSubGroupCount = 293,
        GetKernelNDrangeMaxSubGroupSize = 294,
        GetKernelWorkGroupSize = 295,
        GetKernelPreferredWorkGroupSizeMultiple = 296,
        RetainEvent = 297,
        ReleaseEvent = 298,
        CreateUserEvent = 299,
        IsValidEvent = 300,
        SetUserEventStatus = 301,
        CaptureEventProfilingInfo = 302,
        GetDefaultQueue = 303,
        BuildNDRange = 304,
        ImageSparseSampleImplicitLod = 305,
        ImageSparseSampleExplicitLod = 306,
        ImageSparseSampleDrefImplicitLod = 307,
        ImageSparseSampleDrefExplicitLod = 308,
        ImageSparseSampleProjImplicitLod = 309,
        ImageSparseSampleProjExplicitLod = 310,
        ImageSparseSampleProjDrefImplicitLod = 311,
        ImageSparseSampleProjDrefExplicitLod = 312,
        ImageSparseFetch = 313,
        ImageSparseGather = 314,
        ImageSparseDrefGather = 315,
        ImageSparseTexelsResident = 316,
        NoLine = 317,
        AtomicFlagTestAndSet = 318,
        AtomicFlagClear = 319,
        ImageSparseRead = 320,
        SizeOf = 321,
        TypePipeStorage = 322,
        ConstantPipeStorage = 323,
        CreatePipeFromPipeStorage = 324,
        GetKernelLocalSizeForSubgroupCount = 325,
        GetKernelMaxNumSubgroups = 326,
        TypeNamedBarrier = 327,
        NamedBarrierInitialize = 328,
        MemoryNamedBarrier = 329,
        ModuleProcessed = 330,
        ExecutionModeId = 331,
        DecorateId = 332,
        GroupNonUniformElect = 333,
        GroupNonUniformAll = 334,
        GroupNonUniformAny = 335,
        GroupNonUniformAllEqual = 336,
        GroupNonUniformBroadcast = 337,
        GroupNonUniformBroadcastFirst = 338,
        GroupNonUniformBallot = 339,
        GroupNonUniformInverseBallot = 340,
        GroupNonUniformBallotBitExtract = 341,
        GroupNonUniformBallotBitCount = 342,
        GroupNonUniformBallotFindLSB = 343,
        GroupNonUniformBallotFindMSB = 344,
        GroupNonUniformShuffle = 345,
        GroupNonUniformShuffleXor = 346,
        GroupNonUniformShuffleUp = 347,
        GroupNonUniformShuffleDown = 348,
        GroupNonUniformIAdd = 349,
        GroupNonUniformFAdd = 350,
        GroupNonUniformIMul = 351,
        GroupNonUniformFMul = 352,
        GroupNonUniformSMin = 353,
        GroupNonUniformUMin = 354,
        GroupNonUniformFMin = 355,
        GroupNonUniformSMax = 356,
        GroupNonUniformUMax = 357,
        GroupNonUniformFMax = 358,
        GroupNonUniformBitwiseAnd = 359,
        GroupNonUniformBitwiseOr = 360,
        GroupNonUniformBitwiseXor = 361,
        GroupNonUniformLogicalAnd = 362,
        GroupNonUniformLogicalOr = 363,
        GroupNonUniformLogicalXor = 364,
        GroupNonUniformQuadBroadcast = 365,
        GroupNonUniformQuadSwap = 366,
        SubgroupBallotKHR = 4421,
        SubgroupFirstInvocationKHR = 4422,
        SubgroupAllKHR = 4428,
        SubgroupAnyKHR = 4429,
        SubgroupAllEqualKHR = 4430,
        SubgroupReadInvocationKHR = 4432,
        GroupIAddNonUniformAMD = 5000,
        GroupFAddNonUniformAMD = 5001,
        GroupFMinNonUniformAMD = 5002,
        GroupUMinNonUniformAMD = 5003,
        GroupSMinNonUniformAMD = 5004,
        GroupFMaxNonUniformAMD = 5005,
        GroupUMaxNonUniformAMD = 5006,
        GroupSMaxNonUniformAMD = 5007,
        FragmentMaskFetchAMD = 5011,
        FragmentFetchAMD = 5012,
        ImageSampleFootprintNV = 5283,
        GroupNonUniformPartitionNV = 5296,
        WritePackedPrimitiveIndices4x8NV = 5299,
        ReportIntersectionNV = 5334,
        IgnoreIntersectionNV = 5335,
        TerminateRayNV = 5336,
        TraceNV = 5337,
        TypeAccelerationStructureNV = 5341,
        ExecuteCallableNV = 5344,
        TypeCooperativeMatrixNV = 5358,
        CooperativeMatrixLoadNV = 5359,
        CooperativeMatrixStoreNV = 5360,
        CooperativeMatrixMulAddNV = 5361,
        CooperativeMatrixLengthNV = 5362,
        SubgroupShuffleINTEL = 5571,
        SubgroupShuffleDownINTEL = 5572,
        SubgroupShuffleUpINTEL = 5573,
        SubgroupShuffleXorINTEL = 5574,
        SubgroupBlockReadINTEL = 5575,
        SubgroupBlockWriteINTEL = 5576,
        SubgroupImageBlockReadINTEL = 5577,
        SubgroupImageBlockWriteINTEL = 5578,
        SubgroupImageMediaBlockReadINTEL = 5580,
        SubgroupImageMediaBlockWriteINTEL = 5581,
        DecorateStringGOOGLE = 5632,
        MemberDecorateStringGOOGLE = 5633
    }
}
